branches:
  only:
    - master

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-26.0.3
    - android-26
    - android-23
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-21

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.android/build-cache
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.npm
    - $HOME/.nvm

install:
    - echo no | npm install -g nativescript
    - tns usage-reporting disable
    - tns error-reporting disable
    - npm i
    - npm run compile

matrix:
  include:
    - stage: "Lint"
      language: node_js
      os: linux
      node_js: "6"
      script:
        - npm run tslint
    - stage: "Build, webpack and test"
      language: android
      os: linux
      jdk: oraclejdk8
      env:
        - Android="Build"
      before_install:
        - nvm install 6
      script:
        - cd demo
        - npm i
        - tns build android
        - cd ../demo-angular
        - npm i
        - tns build android
    - language: android
      os: linux
      jdk: oraclejdk8
      env:
        - Android="Webpack"
      before_install:
        - nvm install 6
      script:
        - cd demo
        - npm i
        - tns build android --bundle --env.uglify --env.snapshot
        - cd ../demo-angular
        - npm i
        - tns build android --bundle --env.uglify --env.snapshot
    - language: android
      os: linux
      dist: precise
      jdk: oraclejdk8
      env:
        - Android="Test"
      before_install:
        - nvm install 6
      before_script:
        - echo no | android create avd --force -n test -t android-21 -b armeabi-v7a
        - emulator -avd test -no-audio -no-window &
        - android-wait-for-emulator
        - adb shell input keyevent 82 &
      script:
        - cd demo
        - npm i
        - tns build android
        - tns test android --emulator --justlaunch
        - cd ../demo-angular
        - npm i
        - tns build android
        - tns test android --emulator --justlaunch
    - os: osx
      osx_image: xcode9.1
      language: node_js
      node_js: "6"
      jdk: oraclejdk8
      env:
        - iOS="Build"
      script:
        - cd demo
        - npm i
        - tns build ios
        - cd ../demo-angular
        - npm i
        - tns build ios
    - os: osx
      osx_image: xcode9.1
      language: node_js
      node_js: "6"
      jdk: oraclejdk8
      env:
        - iOS="Webpack"
      script:
        - cd demo
        - npm i
        - tns build ios --bundle --env.uglify
        - cd ../demo-angular
        - npm i
        - tns build ios --bundle --env.uglify
    - os: osx
      osx_image: xcode8.3
      language: node_js
      node_js: "6"
      jdk: oraclejdk8
      env:
        - iOS="Test"
      script:
        - cd demo
        - npm i
        - tns build ios
        - tns test ios --emulator --justlaunch
        - cd ../demo-angular
        - npm i
        - tns build ios
        - tns test ios --emulator --justlaunch
